#include "buildup_tests_support.h"

void buildup_rejects_queue_order_mismatch(void);
void buildup_event_preserves_board_before_and_after(void);
void packing_candidate_converts_to_buildup_problem(void);
void buildup_state_starts_from_problem_initial_board_hold_and_cursor(void);
void buildup_state_contains_deleted_line_state(void);
void buildup_state_contains_hold_automaton_state(void);
void buildup_memo_key_differs_by_deleted_line_state(void);
void buildup_memo_key_differs_by_bag_epoch(void);
void buildup_memo_key_differs_by_bag_remainder_key(void);
void buildup_memo_key_differs_by_reachability_state(void);
void mvp1_buildup_15_operation_fast_path_unchanged(void);
void operation_count_above_runtime_limit_is_unsupported(void);
void board128_buildup_guard_reports_unsupported(void);
void unsupported_buildup_scope_does_not_claim_solution(void);
void y_adjustment_uses_deleted_row_mask_not_deleted_count(void);
void geometry_variant_domain_survives_intermediate_line_clear(void);
void buildup_worker_uses_search_height_when_visible_height_differs(void);
void failed_memo_hash_collision_does_not_merge_distinct_hold_states(void);
void failed_memo_compares_piece_source_id_exactly(void);
void failed_memo_compares_bag_epoch_exactly(void);
void failed_memo_compares_bag_remainder_key_exactly(void);
void failed_memo_compares_provenance_exactly(void);
void failed_memo_compares_hold_piece_and_empty_exactly(void);
void failed_memo_compares_cursor_exactly(void);
void reachability_capacity_exceeded_is_incomplete_not_impossible(void);
void reachability_invalid_kick_table_is_fatal_not_unreachable(void);
void incomplete_branch_prevents_failed_memo_insert(void);
void fatal_branch_prevents_failed_memo_insert(void);
void failed_memo_requires_all_branches_exhaustively_rejected(void);
void build_variant_preserves_packing_candidate_id(void);
void packing_possible_but_queue_order_impossible_fixture(void);
void packing_possible_but_hold_disabled_impossible_fixture(void);
void packing_possible_but_line_clear_y_adjustment_impossible_fixture(void);
void packing_possible_but_srs_reachability_impossible_fixture(void);
void buildup_reachability_bridge_uses_no_kick_srs_srs_plus_and_imported_tables(void);
void bag_aligned_pattern_duplicate_is_not_a_build_variant_fixture(void);
void representative_order_hint_is_priority_not_single_path_fixture(void);
void buildup_exports_actual_success_operation_order(void);
void valid_packing_and_valid_buildup_becomes_build_variant_fixture(void);
void build_up_bfs_matches_fixture(void);
void buildup_modes_split_verify_first_enumerate_and_count(void);
void buildup_verify_first_returns_single_witness(void);
void buildup_enumerate_variants_returns_expected_count_for_two_operation_fixture(void);
void buildup_count_variants_matches_enumerate_variants_for_small_fixture(void);
void buildup_count_variants_reports_total_count_without_retaining_traces(void);
void count_variants_zero_solution_is_complete(void);
void count_variants_zero_max_variants_uses_default_budget(void);
void enumerate_and_count_zero_max_variants_have_same_default_semantics(void);
void enumerate_variants_truncates_after_limit_without_losing_prefix(void);
void build_up_count_reports_truncation(void);
void enumerate_variants_retention_limit_preserves_complete_count(void);
void enumerate_variants_preserves_hold_branches(void);
void buildup_enumerate_variants_preserves_hold_branches(void);
void buildup_enumerate_variants_returns_multiple_hold_branches(void);
void buildup_enumerate_variants_preserves_hold_branch_kind(void);
void enumerate_variants_always_preserves_hold_branches(void);
void coverage_mode_never_calls_consume_first_branch_only(void);
void build_variant_exports_hold_branch_kind(void);
void hold_decision_sequence_is_preserved(void);
void count_variants_reports_complete_count_without_retaining_all_traces(void);
void fixed_queue_tio_not_reordered_to_iot(void);
void fixed_queue_order_not_reordered_by_multiset(void);
void fixed_queue_same_multiset_different_order_changes_buildability(void);
void same_multiset_different_queue_changes_buildability(void);
void hold_disabled_uses_actual_queue_order(void);
void hold_enabled_long_carryover_uses_piece_source_pattern(void);
void long_hold_carryover_uses_bag_epoch_and_remainder(void);
void terminal_projection_branch_is_exactly_once_and_terminal_only(void);
void terminal_projection_builds_with_occupied_initial_hold(void);
void piece_source_reader_rejects_provenance_mismatch(void);
void hold_transition_updates_bag_epoch_and_remainder_from_piece_source_pattern(void);
void bag_universe_pattern_id_controls_sequence(void);
void bag_pattern_id_changes_hold_reachable_language(void);
void bag_universe_allows_duplicate_across_bag_epoch(void);
void materialized_pattern_reader_preserves_pattern_order(void);
void synthetic_multiset_queue_is_forbidden(void);
void c_build_variant_exports_kick_evidence(void);
void build_variant_exports_kick_evidence(void);
void actual_reachability_kick_evidence_reaches_build_variant(void);
void kick_evidence_buffer_reports_capacity_exhausted(void);
void kick_evidence_buffer_budget_rejects_exhaustion(void);
void kick_evidence_missing_sets_trace_completeness_flag(void);
void kick_profile_without_rotation_evidence_remains_complete(void);
void same_operation_set_different_order_produces_distinct_trace_identity(void);
void prepared_geometry_language_v2_exports_semantic_nodes_and_edges(void);
void geometry_only_transition_does_not_share_reachability_cache_entries(void);

int main(void) {
    buildup_rejects_queue_order_mismatch();
    buildup_event_preserves_board_before_and_after();
    packing_candidate_converts_to_buildup_problem();
    buildup_state_starts_from_problem_initial_board_hold_and_cursor();
    buildup_state_contains_deleted_line_state();
    buildup_state_contains_hold_automaton_state();
    buildup_memo_key_differs_by_deleted_line_state();
    buildup_memo_key_differs_by_bag_epoch();
    buildup_memo_key_differs_by_bag_remainder_key();
    buildup_memo_key_differs_by_reachability_state();
    mvp1_buildup_15_operation_fast_path_unchanged();
    operation_count_above_runtime_limit_is_unsupported();
    board128_buildup_guard_reports_unsupported();
    unsupported_buildup_scope_does_not_claim_solution();
    y_adjustment_uses_deleted_row_mask_not_deleted_count();
    geometry_variant_domain_survives_intermediate_line_clear();
    buildup_worker_uses_search_height_when_visible_height_differs();
    failed_memo_hash_collision_does_not_merge_distinct_hold_states();
    failed_memo_compares_piece_source_id_exactly();
    failed_memo_compares_bag_epoch_exactly();
    failed_memo_compares_bag_remainder_key_exactly();
    failed_memo_compares_provenance_exactly();
    failed_memo_compares_hold_piece_and_empty_exactly();
    failed_memo_compares_cursor_exactly();
    reachability_capacity_exceeded_is_incomplete_not_impossible();
    reachability_invalid_kick_table_is_fatal_not_unreachable();
    incomplete_branch_prevents_failed_memo_insert();
    fatal_branch_prevents_failed_memo_insert();
    failed_memo_requires_all_branches_exhaustively_rejected();
    build_variant_preserves_packing_candidate_id();
    packing_possible_but_queue_order_impossible_fixture();
    packing_possible_but_hold_disabled_impossible_fixture();
    packing_possible_but_line_clear_y_adjustment_impossible_fixture();
    packing_possible_but_srs_reachability_impossible_fixture();
    buildup_reachability_bridge_uses_no_kick_srs_srs_plus_and_imported_tables();
    bag_aligned_pattern_duplicate_is_not_a_build_variant_fixture();
    representative_order_hint_is_priority_not_single_path_fixture();
    buildup_exports_actual_success_operation_order();
    valid_packing_and_valid_buildup_becomes_build_variant_fixture();
    build_up_bfs_matches_fixture();
    buildup_modes_split_verify_first_enumerate_and_count();
    buildup_verify_first_returns_single_witness();
    buildup_enumerate_variants_returns_expected_count_for_two_operation_fixture();
    buildup_count_variants_matches_enumerate_variants_for_small_fixture();
    buildup_count_variants_reports_total_count_without_retaining_traces();
    count_variants_zero_solution_is_complete();
    count_variants_zero_max_variants_uses_default_budget();
    enumerate_and_count_zero_max_variants_have_same_default_semantics();
    enumerate_variants_truncates_after_limit_without_losing_prefix();
    build_up_count_reports_truncation();
    enumerate_variants_retention_limit_preserves_complete_count();
    enumerate_variants_preserves_hold_branches();
    buildup_enumerate_variants_preserves_hold_branches();
    buildup_enumerate_variants_returns_multiple_hold_branches();
    buildup_enumerate_variants_preserves_hold_branch_kind();
    enumerate_variants_always_preserves_hold_branches();
    coverage_mode_never_calls_consume_first_branch_only();
    build_variant_exports_hold_branch_kind();
    hold_decision_sequence_is_preserved();
    count_variants_reports_complete_count_without_retaining_all_traces();
    fixed_queue_tio_not_reordered_to_iot();
    fixed_queue_order_not_reordered_by_multiset();
    fixed_queue_same_multiset_different_order_changes_buildability();
    same_multiset_different_queue_changes_buildability();
    hold_disabled_uses_actual_queue_order();
    hold_enabled_long_carryover_uses_piece_source_pattern();
    long_hold_carryover_uses_bag_epoch_and_remainder();
    terminal_projection_branch_is_exactly_once_and_terminal_only();
    terminal_projection_builds_with_occupied_initial_hold();
    piece_source_reader_rejects_provenance_mismatch();
    hold_transition_updates_bag_epoch_and_remainder_from_piece_source_pattern();
    bag_universe_pattern_id_controls_sequence();
    bag_pattern_id_changes_hold_reachable_language();
    bag_universe_allows_duplicate_across_bag_epoch();
    materialized_pattern_reader_preserves_pattern_order();
    synthetic_multiset_queue_is_forbidden();
    c_build_variant_exports_kick_evidence();
    build_variant_exports_kick_evidence();
    actual_reachability_kick_evidence_reaches_build_variant();
    kick_evidence_buffer_reports_capacity_exhausted();
    kick_evidence_buffer_budget_rejects_exhaustion();
    kick_evidence_missing_sets_trace_completeness_flag();
    kick_profile_without_rotation_evidence_remains_complete();
    same_operation_set_different_order_produces_distinct_trace_identity();
    prepared_geometry_language_v2_exports_semantic_nodes_and_edges();
    geometry_only_transition_does_not_share_reachability_cache_entries();
    puts("core-c buildup tests passed");
    return 0;
}
