#include "packing_tests_support.h"

void packing_candidate_is_not_solution_before_buildup(void);
void two_line_empty_board_packing_candidates_generated(void);
void problem_descriptor_packing_candidates_generated(void);
void problem_descriptor_capacity_preserves_candidates_and_resource_report(void);
void packing_problem_allows_piece_multiset_supply_superset_of_search_window(void);
void problem_descriptor_uses_search_height_for_layout_when_visible_height_differs(void);
void exact_piece_window_short_queue_is_empty_result_not_invalid(void);
void non_exact_piece_window_clamps_to_available_queue(void);
void placement_candidate_preserves_same_mask_different_rotation(void);
void same_mask_different_operation_id_not_dropped_before_buildup(void);
void placement_geometry_class_retains_operation_variants(void);
void build_up_tries_next_operation_variant_when_first_variant_unreachable(void);
void kick_sensitive_replay_not_lost_by_mask_dedupe(void);
void custom_piece_same_mask_different_definition_not_deduped(void);
void candidate_buffer_is_soa(void);
void shape_key_stable(void);
void tiling_key_stable(void);
void same_shape_different_tiling_not_deduped_by_shape(void);
void same_masks_different_piece_identity_not_same_tiling_key(void);
void custom_piece_same_mask_different_definition_not_same_tiling_key(void);
void same_mask_different_piece_definition_not_same_tiling(void);
void shape_family_visual_grouping_does_not_drop_tiling_variant(void);
void shape_key_does_not_drop_tiling_variant(void);
void tiling_key_does_not_drop_build_variant(void);
void operation_set_key_stable(void);
void hash_collision_exact_confirm_works(void);
void same_operation_set_deduped(void);
void packing_deduper_preserves_distinct_operation_sets(void);
void different_operation_set_preserved(void);
void candidate_identity_includes_final_board_and_cleared_lines(void);
void hash_collision_preserved_by_exact_confirm(void);
void candidate_ids_stable_across_cpu_gpu_backend_order(void);
void candidate_buffer_exports_canonical_identity(void);
void geometry_catalog_collapses_skeletons_without_losing_realizations(void);
void geometry_catalog_preserves_prefix_deleted_clear_state_realization(void);
void full_placement_domain_rejects_overlapping_exact_owner_sets(void);
void geometry_dynamic_pruning_respects_evidence_policy(void);
void geometry_catalog_view_is_pointer_stable_across_search(void);
void geometry_catalog_identity_is_independent_of_piece_multiset(void);
void exact_cover_partition_union_matches_serial(void);
void residual_memo_requires_exact_piece_counts(void);
void residual_memo_saturation_keeps_search_authority(void);
void solution_family_uses_stable_row_id_dag(void);
void solution_family_product_streams_cartesian_paths_lazily(void);
void disconnected_component_join_has_single_canonical_owner(void);
void hypergraph_components_require_absent_cross_component_rows(void);
void disconnected_exact_cover_uses_lazy_component_product(void);
void exact_cover_graph_streams_immutable_row_paths(void);
void exact_cover_graph_represents_complete_empty_result(void);
void realization_feasibility_preserves_buildable_four_line_geometry(void);
void exact_cover_graph_feeds_buildup_without_candidate_batch(void);

int main(void) {
    packing_candidate_is_not_solution_before_buildup();
    two_line_empty_board_packing_candidates_generated();
    problem_descriptor_packing_candidates_generated();
    problem_descriptor_capacity_preserves_candidates_and_resource_report();
    packing_problem_allows_piece_multiset_supply_superset_of_search_window();
    problem_descriptor_uses_search_height_for_layout_when_visible_height_differs();
    exact_piece_window_short_queue_is_empty_result_not_invalid();
    non_exact_piece_window_clamps_to_available_queue();
    placement_candidate_preserves_same_mask_different_rotation();
    same_mask_different_operation_id_not_dropped_before_buildup();
    placement_geometry_class_retains_operation_variants();
    build_up_tries_next_operation_variant_when_first_variant_unreachable();
    kick_sensitive_replay_not_lost_by_mask_dedupe();
    custom_piece_same_mask_different_definition_not_deduped();
    candidate_buffer_is_soa();
    shape_key_stable();
    tiling_key_stable();
    same_shape_different_tiling_not_deduped_by_shape();
    same_masks_different_piece_identity_not_same_tiling_key();
    custom_piece_same_mask_different_definition_not_same_tiling_key();
    same_mask_different_piece_definition_not_same_tiling();
    shape_family_visual_grouping_does_not_drop_tiling_variant();
    shape_key_does_not_drop_tiling_variant();
    tiling_key_does_not_drop_build_variant();
    operation_set_key_stable();
    hash_collision_exact_confirm_works();
    same_operation_set_deduped();
    packing_deduper_preserves_distinct_operation_sets();
    different_operation_set_preserved();
    candidate_identity_includes_final_board_and_cleared_lines();
    hash_collision_preserved_by_exact_confirm();
    candidate_ids_stable_across_cpu_gpu_backend_order();
    candidate_buffer_exports_canonical_identity();
    geometry_catalog_collapses_skeletons_without_losing_realizations();
    geometry_catalog_preserves_prefix_deleted_clear_state_realization();
    full_placement_domain_rejects_overlapping_exact_owner_sets();
    geometry_dynamic_pruning_respects_evidence_policy();
    geometry_catalog_view_is_pointer_stable_across_search();
    geometry_catalog_identity_is_independent_of_piece_multiset();
    exact_cover_partition_union_matches_serial();
    residual_memo_requires_exact_piece_counts();
    residual_memo_saturation_keeps_search_authority();
    solution_family_uses_stable_row_id_dag();
    solution_family_product_streams_cartesian_paths_lazily();
    disconnected_component_join_has_single_canonical_owner();
    hypergraph_components_require_absent_cross_component_rows();
    disconnected_exact_cover_uses_lazy_component_product();
    exact_cover_graph_streams_immutable_row_paths();
    exact_cover_graph_represents_complete_empty_result();
    realization_feasibility_preserves_buildable_four_line_geometry();
    exact_cover_graph_feeds_buildup_without_candidate_batch();
    puts("core-c packing tests passed");
    return 0;
}
