#ifndef CLEARRA_HYBRID_STATUS_H
#define CLEARRA_HYBRID_STATUS_H
typedef enum ClearraHybridStatus {
    CLEARRA_HYBRID_OK = 0,
    CLEARRA_HYBRID_INVALID_ARGUMENT = 1,
    CLEARRA_HYBRID_GPU_UNAVAILABLE = 2,
    CLEARRA_HYBRID_PACKING_ERROR = 3,
    CLEARRA_HYBRID_BUILDUP_ERROR = 4,
    CLEARRA_HYBRID_MEMORY_ERROR = 5,
    CLEARRA_HYBRID_RESULT_MISMATCH = 6
} ClearraHybridStatus;typedef enum ClearraHybridFailureStage {
    CLEARRA_HYBRID_STAGE_NONE = 0,
    CLEARRA_HYBRID_STAGE_GPU_WORKER = 1,
    CLEARRA_HYBRID_STAGE_GPU_PACKING = 2,
    CLEARRA_HYBRID_STAGE_CONFIRMED_QUEUE = 3,
    CLEARRA_HYBRID_STAGE_SCRATCH = 4,
    CLEARRA_HYBRID_STAGE_CPU_REFERENCE_PACKING = 5,
    CLEARRA_HYBRID_STAGE_CPU_BUILDUP = 6,
    CLEARRA_HYBRID_STAGE_HYBRID_BUILDUP = 7,
    CLEARRA_HYBRID_STAGE_CPU_COVERAGE = 8,
    CLEARRA_HYBRID_STAGE_HYBRID_COVERAGE = 9,
    CLEARRA_HYBRID_STAGE_RESULT_COMPARE = 10,
    CLEARRA_HYBRID_STAGE_MEMORY_EPOCH = 11
} ClearraHybridFailureStage;
#endif
