option(CLEARRA_CORE_ENABLE_ASAN "Build core-c with AddressSanitizer when supported." OFF)
option(CLEARRA_CORE_ENABLE_UBSAN "Build core-c with UndefinedBehaviorSanitizer when supported." OFF)

add_library(clearra_core_sanitizer_options INTERFACE)
if(MSVC)
    if(CLEARRA_CORE_ENABLE_ASAN)
        target_compile_options(clearra_core_sanitizer_options INTERFACE /fsanitize=address)
        target_link_options(clearra_core_sanitizer_options INTERFACE /fsanitize=address)
    endif()
    if(CLEARRA_CORE_ENABLE_UBSAN)
        message(WARNING "UBSan is unavailable for the MSVC C compiler; building without it.")
    endif()
else()
    if(CLEARRA_CORE_ENABLE_ASAN)
        target_compile_options(clearra_core_sanitizer_options INTERFACE -fsanitize=address -fno-omit-frame-pointer)
        target_link_options(clearra_core_sanitizer_options INTERFACE -fsanitize=address)
    endif()
    if(CLEARRA_CORE_ENABLE_UBSAN)
        target_compile_options(clearra_core_sanitizer_options INTERFACE -fsanitize=undefined -fno-omit-frame-pointer)
        target_link_options(clearra_core_sanitizer_options INTERFACE -fsanitize=undefined)
    endif()
endif()
