use crate::commands::{bool_field, number_field, string_field};

pub(super) fn scenario_field(key: String, value: String) -> clearra_output::model::RenderField {
    if SCENARIO_BOOL_KEYS.contains(&key.as_str()) {
        return match value.as_str() {
            "true" => bool_field(key, true),
            "false" => bool_field(key, false),
            _ => string_field(key, value),
        };
    }
    if SCENARIO_NUMBER_KEYS.contains(&key.as_str()) && value != "none" {
        return number_field(key, value);
    }
    string_field(key, value)
}

const SCENARIO_BOOL_KEYS: &[&str] = &[
    "actual_unsupported",
    "allow_hold",
    "backend_fallback_allowed",
    "backend_fallback_used",
    "budget_exceeded",
    "continue_available",
    "continuation_available",
    "continuation_available_complete",
    "continuation_enough_queue_for_next_pc",
    "continuation_token_available",
    "count_complete",
    "count_requested",
    "cpu_confirmed",
    "expected_checked",
    "expected_match",
    "expected_unsupported",
    "execution_deterministic",
    "gpu_backend_available",
    "gpu_confirmed",
    "interactive_prompt",
    "multiplicity_count_available",
    "minimum_cover_complete",
    "minimum_cover_proven_minimum",
    "minimum_cover_requested",
    "native_c_core_executed",
    "native_c_core_linked",
    "next_pc_available",
    "normalized_solution_set_checked",
    "normalized_solution_set_match",
    "objective_complete",
    "objective_search_complete",
    "placement_event_available",
    "postprocess_execution_complete",
    "probability_complete",
    "requires_180",
    "retained_trace_keys_checked",
    "retained_trace_keys_match",
    "sample_trace_available",
    "score_core_hot_path",
    "score_does_not_change_probability_union",
    "score_evaluation_complete",
    "score_best_complete",
    "score_all_universe_patterns_covered",
    "score_hard_drop_included",
    "score_soft_drop_included",
    "score_level_system_enabled",
    "score_post_processing",
    "score_requested",
    "score_summary_complete",
    "score_matrix_complete",
    "score_matrix_materialized",
    "score_profile_specific_exact",
    "solution_found",
    "solution_trace_available",
    "state_count_available",
    "trace_available",
    "trace_retention_truncated",
    "verified_profile",
    "clear_event_available",
    "drop_event_basis_available",
    "spin_event_basis_available",
];

const SCENARIO_NUMBER_KEYS: &[&str] = &[
    "board_width",
    "budget_exceeded_count",
    "build_variant_count",
    "checkpoint_schedule_checkpoint_count",
    "cleared_lines",
    "continuation_queue_consumed",
    "coverage_probability",
    "coverage_pattern_count",
    "coverage_row_count",
    "covered_pattern_count",
    "duplicate_transition_count",
    "exact_pieces",
    "execution_max_frontier_states",
    "execution_max_candidates",
    "execution_max_patterns",
    "execution_max_memory_mib",
    "execution_workers",
    "expected_retained_trace_key_count",
    "expected_total_solution_count",
    "issue_count",
    "missing_transition_count",
    "min_queue_consumed",
    "min_remaining_queue",
    "max_queue_consumed",
    "objective_coverage_matrix_rows",
    "objective_solution_traces",
    "objective_unique_solution_traces",
    "packing_candidate_count",
    "piece_window",
    "placed_piece_count",
    "placed_pieces",
    "postprocess_execution_count",
    "postprocess_pattern_weight_count",
    "queue_len",
    "remaining_queue_len",
    "retained_trace_count",
    "retained_trace_key_count",
    "retained_trace_limit",
    "sample_queue_consumed",
    "score_best_attack",
    "score_best_score",
    "score_covered_pattern_conditional_average_score",
    "score_covered_probability",
    "score_event_count",
    "score_initial_b2b",
    "score_all_clear_b2b_extra_increment",
    "score_level_multiplier",
    "score_matrix_cell_count",
    "score_matrix_pattern_count",
    "score_failed_pc_pattern_count",
    "score_failed_pc_pattern_score",
    "score_field_average_score",
    "score_representative_attack",
    "score_representative_score",
    "score_pattern_optimal_count",
    "score_unconditional_expected_attack",
    "score_unconditional_expected_score",
    "score_evaluation_trace_count",
    "score_probability_after",
    "score_probability_before",
    "searched_nodes",
    "search_nodes",
    "solution_trace_count",
    "supply_covered_pattern_count",
    "supply_boundary_candidates",
    "total_solution_count",
    "trace_steps",
    "unique_solution_count",
    "minimum_cover_required_pattern_count",
    "minimum_cover_selected_solution_count",
    "minimum_cover_source_solution_count",
    "unique_solution_trace_count",
    "validation_error_count",
    "workers_used",
];
