#ifndef CLR_PROBLEM_POLICY_H
#define CLR_PROBLEM_POLICY_H

#define CLR_PROBLEM_OPENING_PC 1u
#define CLR_PROBLEM_SCENARIO_PC 2u
#define CLR_PROBLEM_SETUP 3u
#define CLR_PROBLEM_BUILD 4u

#define CLR_GOAL_CLEAR_TO_EMPTY 1u

#define CLR_COUNT_FIRST_SOLUTION 1u
#define CLR_COUNT_ALL 2u
#define CLR_COUNT_UNIQUE 3u

#define CLR_OBJECTIVE_ALL 1u
#define CLR_OBJECTIVE_UNIQUE 2u
#define CLR_OBJECTIVE_MIN_COVER 3u

#define CLR_BACKEND_AUTO 0u
#define CLR_BACKEND_CPU 5u
#define CLR_BACKEND_GPU 6u
#define CLR_BACKEND_HYBRID 7u

#define CLR_BACKEND_FALLBACK_ALLOW 1u
#define CLR_BACKEND_FALLBACK_DENY 2u

#endif
