#ifndef CLR_BUILDUP_STATUS_H
#define CLR_BUILDUP_STATUS_H

#define CLR_BUILDUP_MAX_OPERATIONS 15u
#define CLR_BUILDUP_MAX_VARIANTS 512u
#define CLR_BUILDUP_MAX_KICK_EVIDENCE_PER_VARIANT 16u
#define CLR_BUILDUP_TRACE_COMPLETENESS_KICK_EVIDENCE_MISSING 1u
#define CLR_LINE_CLEAR_POLICY_STANDARD 1u

#define CLR_BUILDUP_MODE_VERIFY_FIRST 1u
#define CLR_BUILDUP_MODE_ENUMERATE_VARIANTS 2u
#define CLR_BUILDUP_MODE_COUNT_VARIANTS 3u
#define CLR_BUILDUP_FLAG_HOLD_ENABLED 1u

typedef enum clr_buildup_status {
    CLR_BUILDUP_OK = 0,
    CLR_BUILDUP_INVALID_ARGUMENT = 1,
    CLR_BUILDUP_INVALID_PROBLEM = 2,
    CLR_BUILDUP_INVALID_ORDER = 3,
    CLR_BUILDUP_LINE_CLEAR_DEPENDENCY_IMPOSSIBLE = 4,
    CLR_BUILDUP_Y_ADJUSTMENT_IMPOSSIBLE = 5,
    CLR_BUILDUP_NOT_GROUNDED = 6,
    CLR_BUILDUP_REACHABILITY_IMPOSSIBLE = 7,
    CLR_BUILDUP_QUEUE_ORDER_IMPOSSIBLE = 8,
    CLR_BUILDUP_HOLD_DISABLED_IMPOSSIBLE = 9,
    CLR_BUILDUP_BAG_PATTERN_IMPOSSIBLE = 10,
    CLR_BUILDUP_PIECE_WINDOW_IMPOSSIBLE = 11,
    CLR_BUILDUP_GOAL_NOT_SATISFIED = 12,
    CLR_BUILDUP_COLLISION = 13,
    CLR_BUILDUP_CAPACITY_EXCEEDED = 14,
    CLR_KICK_EVIDENCE_BUFFER_EXHAUSTED = 15,
    CLR_BUILDUP_ENUMERATION_TRUNCATED = 16,
    CLR_BUILDUP_UNSUPPORTED_RUNTIME_SCOPE = 17,
    CLR_BUILDUP_CANCELLED = 18
} clr_buildup_status;

#endif
