use super::diagnostic_code::DiagnosticCode;

impl DiagnosticCode {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::ESupplyInvalidDuplicate => "E_SUPPLY_INVALID_DUPLICATE",
            Self::ESupplyInvalidBagBoundary => "E_SUPPLY_INVALID_BAG_BOUNDARY",
            Self::WSupplyAmbiguousObservedWindow => "W_SUPPLY_AMBIGUOUS_OBSERVED_WINDOW",
            Self::ISupplyBoundaryCompatible => "I_SUPPLY_BOUNDARY_COMPATIBLE",
            Self::ISupplyFixedSequenceAccepted => "I_SUPPLY_FIXED_SEQUENCE_ACCEPTED",
            Self::WFastPathTwoLineDisabled => "W_FAST_PATH_TWO_LINE_DISABLED",
            Self::IFastPathTwoLineEnabled => "I_FAST_PATH_TWO_LINE_ENABLED",
            Self::WMinimumCoverGreedyFallback => "W_MINIMUM_COVER_GREEDY_FALLBACK",
            Self::WPcObjectiveFirstSolutionFallback => "W_PC_OBJECTIVE_FIRST_SOLUTION_FALLBACK",
            Self::WPcBackendFallback => "W_PC_BACKEND_FALLBACK",
            Self::EBackendGpuFeatureDisabled => "E_BACKEND_GPU_FEATURE_DISABLED",
            Self::EBackendGpuDeviceNotFound => "E_BACKEND_GPU_DEVICE_NOT_FOUND",
            Self::EBackendFrontierBudgetRequired => "E_BACKEND_FRONTIER_BUDGET_REQUIRED",
            Self::EBackendGpuUnavailable => "E_BACKEND_GPU_UNAVAILABLE",
            Self::EGpuWorkerTrustMismatch => "E_GPU_WORKER_TRUST_MISMATCH",
            Self::WBackendFallbackUsed => "W_BACKEND_FALLBACK_USED",
            Self::WGpuBackendFallback => "W_GPU_BACKEND_FALLBACK",
            Self::WGpuDeviceUnavailable => "W_GPU_DEVICE_UNAVAILABLE",
            Self::WHybridBackpressureActive => "W_HYBRID_BACKPRESSURE_ACTIVE",
            Self::WGpuResultCpuConfirmRequired => "W_GPU_RESULT_CPU_CONFIRM_REQUIRED",
            Self::EGpuWorkerMemoryTicketMissing => "E_GPU_WORKER_MEMORY_TICKET_MISSING",
            Self::EGpuWorkerMissingMemoryTicket => "E_GPU_WORKER_MISSING_MEMORY_TICKET",
            Self::EGpuBufferFenceMissing => "E_GPU_BUFFER_FENCE_MISSING",
            Self::EGpuFenceEpochMissing => "E_GPU_FENCE_EPOCH_MISSING",
            Self::EGpuUnconfirmedProbabilitySource => "E_GPU_UNCONFIRMED_PROBABILITY_SOURCE",
            Self::WGpuBufferReleaseDeferred => "W_GPU_BUFFER_RELEASE_DEFERRED",
            Self::WPendingReleaseQueueNotDrained => "W_PENDING_RELEASE_QUEUE_NOT_DRAINED",
            Self::WMemoryPressureHigh => "W_MEMORY_PRESSURE_HIGH",
            Self::ECoreAbiVersionMismatch => "E_CORE_ABI_VERSION_MISMATCH",
            Self::ENativeCoreUnavailable => "E_NATIVE_CORE_UNAVAILABLE",
            Self::ECorePackingFailed => "E_CORE_PACKING_FAILED",
            Self::ECoreBuildUpFailed => "E_CORE_BUILDUP_FAILED",
            Self::ECoreMemoryContextDoubleRelease => "E_CORE_MEMORY_CONTEXT_DOUBLE_RELEASE",
            Self::ECoreMemoryScopeInvalid => "E_CORE_MEMORY_SCOPE_INVALID",
            Self::ECoreMemoryLeakDetected => "E_CORE_MEMORY_LEAK_DETECTED",
            Self::ECoreFfiBufferBounds => "E_CORE_FFI_BUFFER_BOUNDS",
            Self::ECoreInvalidNativeView => "E_CORE_INVALID_NATIVE_VIEW",
            Self::ECMemoryScopeInvalid => "E_C_MEMORY_SCOPE_INVALID",
            Self::ECMemoryLeakDetected => "E_C_MEMORY_LEAK_DETECTED",
            Self::EPackingCandidateUsedAsSolution => "E_PACKING_CANDIDATE_USED_AS_SOLUTION",
            Self::EBoardUnsupportedMvp => "E_BOARD_UNSUPPORTED_MVP",
            Self::ECustomBoardUnsupportedMvp => "E_CUSTOM_BOARD_UNSUPPORTED_MVP",
            Self::EBoardWidthOutOfScope => "E_BOARD_WIDTH_OUT_OF_SCOPE",
            Self::EBoardBackendNotConnected => "E_BOARD_BACKEND_NOT_CONNECTED",
            Self::EWideBoardRuntimeNotConnected => "E_WIDE_BOARD_RUNTIME_NOT_CONNECTED",
            Self::IBoardMvpSupported => "I_BOARD_MVP_SUPPORTED",
            Self::EPieceSetUnsupportedMvp => "E_PIECE_SET_UNSUPPORTED_MVP",
            Self::ECustomPieceUnsupportedMvp => "E_CUSTOM_PIECE_UNSUPPORTED_MVP",
            Self::ECustomBagUnsupportedMvp => "E_CUSTOM_BAG_UNSUPPORTED_MVP",
            Self::IPieceSetMvpSupported => "I_PIECE_SET_MVP_SUPPORTED",
            Self::ERuleUnsupportedMvp => "E_RULE_UNSUPPORTED_MVP",
            Self::WRuleSrsPlusExtensionsDisabled => "W_RULE_SRS_PLUS_EXTENSIONS_DISABLED",
            Self::IRuleMvpSupported => "I_RULE_MVP_SUPPORTED",
            Self::ECustomRuleInvalid => "E_CUSTOM_RULE_INVALID",
            Self::ICustomRuleVerified => "I_CUSTOM_RULE_VERIFIED",
            Self::EPcTargetUnsupportedMvp => "E_PC_TARGET_UNSUPPORTED_MVP",
            Self::IPcTargetMvpSupported => "I_PC_TARGET_MVP_SUPPORTED",
            Self::EPcQueryInvalid => "E_PC_QUERY_INVALID",
            Self::IPcQueryMvpSupported => "I_PC_QUERY_MVP_SUPPORTED",
            Self::EObjectiveUnsupportedMvp => "E_OBJECTIVE_UNSUPPORTED_MVP",
            Self::IObjectiveMvpSupported => "I_OBJECTIVE_MVP_SUPPORTED",
            Self::WObjectivePatternWeightModelNotMaterialized => {
                "W_OBJECTIVE_PATTERN_WEIGHT_MODEL_NOT_MATERIALIZED"
            }
            Self::ESetupQueryInvalid => "E_SETUP_QUERY_INVALID",
            Self::ISetupQueryMvpSupported => "I_SETUP_QUERY_MVP_SUPPORTED",
            Self::EBuildQueryInvalid => "E_BUILD_QUERY_INVALID",
            Self::IBuildQueryMvpSupported => "I_BUILD_QUERY_MVP_SUPPORTED",
            Self::EScoreProfileInvalid => "E_SCORE_PROFILE_INVALID",
            Self::IScoreProfileMvp2Supported => "I_SCORE_PROFILE_MVP2_SUPPORTED",
            Self::ESpinTargetUnsupported => "E_SPIN_TARGET_UNSUPPORTED",
            Self::ESpinProfileUnverified => "E_SPIN_PROFILE_UNVERIFIED",
            Self::ESpinKickEvidenceMissing => "E_SPIN_KICK_EVIDENCE_MISSING",
            Self::ESpinClassifierIncompatible => "E_SPIN_CLASSIFIER_INCOMPATIBLE",
            Self::EScoreProfileSpinPolicyIncompatible => "E_SCORE_PROFILE_SPIN_POLICY_INCOMPATIBLE",
            Self::EScoreMatrixCapacityExceeded => "E_SCORE_MATRIX_CAPACITY_EXCEEDED",
            Self::ESpinCoverageCapacityExceeded => "E_SPIN_COVERAGE_CAPACITY_EXCEEDED",
            Self::ESpinCoverageUniverseMismatch => "E_SPIN_COVERAGE_UNIVERSE_MISMATCH",
            Self::ECoverageCapacityExceeded => "E_COVERAGE_CAPACITY_EXCEEDED",
            Self::EBuildUpVariantEnumerationTruncated => "E_BUILDUP_VARIANT_ENUMERATION_TRUNCATED",
            Self::EKickEvidenceBufferExhausted => "E_KICK_EVIDENCE_BUFFER_EXHAUSTED",
            Self::EAreaInfeasible => "E_AREA_INFEASIBLE",
            Self::IAreaNecessaryConditionPassed => "I_AREA_NECESSARY_CONDITION_PASSED",
            Self::WSpinClassificationEstimated => "W_SPIN_CLASSIFICATION_ESTIMATED",
            Self::WSpinTargetProbabilityIncomplete => "W_SPIN_TARGET_PROBABILITY_INCOMPLETE",
            Self::WScoreExpectationSampleOnly => "W_SCORE_EXPECTATION_SAMPLE_ONLY",
            Self::WSpecialSpinDescriptorOnly => "W_SPECIAL_SPIN_DESCRIPTOR_ONLY",
            Self::WBuildUpEnumerationTruncated => "W_BUILDUP_ENUMERATION_TRUNCATED",
            Self::WObservedQueueProbabilityIncomplete => "W_OBSERVED_QUEUE_PROBABILITY_INCOMPLETE",
            Self::WTraceRetentionTruncated => "W_TRACE_RETENTION_TRUNCATED",
            Self::EGuiFormInvalid => "E_GUI_FORM_INVALID",
            Self::EGuiFilePathUnsafe => "E_GUI_FILE_PATH_UNSAFE",
            Self::EGuiRenderUnsupported => "E_GUI_RENDER_UNSUPPORTED",
            Self::ERenderRuntimeSvgForbidden => "E_RENDER_RUNTIME_SVG_FORBIDDEN",
            Self::ERenderAssetProvenanceMissing => "E_RENDER_ASSET_PROVENANCE_MISSING",
            Self::EGuiSubprocessForbidden => "E_GUI_SUBPROCESS_FORBIDDEN",
            Self::EFrontendTypedRequestRequired => "E_FRONTEND_TYPED_REQUEST_REQUIRED",
            Self::WGuiBackendFallbackRequired => "W_GUI_BACKEND_FALLBACK_REQUIRED",
            Self::WGuiSettingsLoadFailed => "W_GUI_SETTINGS_LOAD_FAILED",
            Self::WGuiSettingsSaveFailed => "W_GUI_SETTINGS_SAVE_FAILED",
            Self::EExternalPcSourceRegistryInvalid => "E_EXTERNAL_PC_SOURCE_REGISTRY_INVALID",
            Self::EExternalPcSourceMissingRetrievedAt => {
                "E_EXTERNAL_PC_SOURCE_MISSING_RETRIEVED_AT"
            }
            Self::EExternalPcSourceRequiresHumanVerification => {
                "E_EXTERNAL_PC_SOURCE_REQUIRES_HUMAN_VERIFICATION"
            }
        }
    }
}
