steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - apps/clearra-discord-bot/Dockerfile.job-service
      - --build-arg
      - CLEARRA_VERSION=${_CLEARRA_VERSION}
      - --build-arg
      - CLEARRA_CLI_SHA256=${_CLEARRA_CLI_SHA256}
      - -t
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
substitutions:
  _CLEARRA_VERSION: 0.5.1
  _CLEARRA_CLI_SHA256: ""
options:
  logging: CLOUD_LOGGING_ONLY
